version: '3'
services:
  app:
    image: cicd201
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME=root
      # - MONGODB_PASSWORD=Noceo4k16Jp8BaVF
      # - MONGODB_DATABASE=Veganzimu
      - MONGODB_CONNECTION_STRING=mongodb://mongo/cicd201
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
